export const AREA_FILTERS = [
  "All",
  "New this week",
  "LEGO Play",
  "Robotics",
  "Art & Design",
  "VR Lab",
  "3D Printing",
] as const;

export const AREA_OPTIONS = [
  "LEGO Play",
  "Robotics",
  "Art & Design",
  "VR Lab",
  "3D Printing",
] as const;

export const FALLBACK_EQUIPMENT = [
  {
    id: "1",
    qr_code: "spike",
    area: "LEGO Play",
    name: "LEGO Spike Prime kit",
    detail: "Includes hub, motors, sensors",
    quantity_available: 6,
    quantity_total: 8,
    sort_order: 1,
    created_at: new Date(Date.now() - 2 * 864e5).toISOString(),
    updated_at: "",
  },
  {
    id: "2",
    qr_code: "technic",
    area: "LEGO Play",
    name: "LEGO Technic bins",
    detail: "Sorted by element type",
    quantity_available: 12,
    quantity_total: 12,
    sort_order: 2,
    created_at: new Date(Date.now() - 90 * 864e5).toISOString(),
    updated_at: "",
  },
  {
    id: "3",
    qr_code: "mbot",
    area: "Robotics",
    name: "mBot2 robot",
    detail: "Charged and ready",
    quantity_available: 4,
    quantity_total: 10,
    sort_order: 3,
    created_at: new Date(Date.now() - 5 * 864e5).toISOString(),
    updated_at: "",
  },
  {
    id: "4",
    qr_code: "arduino",
    area: "Robotics",
    name: "Arduino starter kit",
    detail: "Breadboard, jumper set, sensor pack",
    quantity_available: 9,
    quantity_total: 15,
    sort_order: 4,
    created_at: new Date(Date.now() - 30 * 864e5).toISOString(),
    updated_at: "",
  },
  {
    id: "5",
    qr_code: "solder",
    area: "Robotics",
    name: "Soldering station",
    detail: "Teacher supervision required",
    quantity_available: 2,
    quantity_total: 3,
    sort_order: 5,
    created_at: new Date(Date.now() - 60 * 864e5).toISOString(),
    updated_at: "",
  },
  {
    id: "6",
    qr_code: "mats",
    area: "Art & Design",
    name: "Cutting mats & knives",
    detail: "Blades replaced weekly",
    quantity_available: 14,
    quantity_total: 16,
    sort_order: 6,
    created_at: new Date(Date.now() - 45 * 864e5).toISOString(),
    updated_at: "",
  },
  {
    id: "7",
    qr_code: "paint",
    area: "Art & Design",
    name: "Acrylic paint set",
    detail: "Restock requested",
    quantity_available: 3,
    quantity_total: 20,
    sort_order: 7,
    created_at: new Date(Date.now() - 20 * 864e5).toISOString(),
    updated_at: "",
  },
  {
    id: "8",
    qr_code: "quest",
    area: "VR Lab",
    name: "Meta Quest 3 headset",
    detail: "Wipe before return",
    quantity_available: 5,
    quantity_total: 6,
    sort_order: 8,
    created_at: new Date(Date.now() - 3 * 864e5).toISOString(),
    updated_at: "",
  },
  {
    id: "9",
    qr_code: "prusa",
    area: "3D Printing",
    name: "Prusa MK4 printer",
    detail: "PLA only",
    quantity_available: 2,
    quantity_total: 4,
    sort_order: 9,
    created_at: new Date(Date.now() - 75 * 864e5).toISOString(),
    updated_at: "",
  },
  {
    id: "10",
    qr_code: "filament",
    area: "3D Printing",
    name: "PLA filament (1 kg)",
    detail: "White, black, red in stock",
    quantity_available: 7,
    quantity_total: 10,
    sort_order: 10,
    created_at: new Date(Date.now() - 10 * 864e5).toISOString(),
    updated_at: "",
  },
] as const;

export const WEEK_MS = 7 * 864e5;
