import QRCode from "qrcode";

/** Ambiguous glyphs excluded (0/O, 1/I/L). */
const ITEM_CODE_CHARS = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";

/** QR payload is the immutable item code (DATA-CONTRACT). */
export async function generateQrDataUrl(qrCode: string): Promise<string> {
  return QRCode.toDataURL(qrCode, {
    errorCorrectionLevel: "M",
    margin: 2,
    width: 184,
    color: { dark: "#141414", light: "#ffffff" },
  });
}

export function slugifyQrCode(name: string) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 48);
}

/** Autogenerated alphanumeric item code, e.g. KIS-7F3K9Q */
export function generateItemCode(prefix = "KIS"): string {
  const bytes = crypto.getRandomValues(new Uint8Array(6));
  let suffix = "";
  for (let i = 0; i < 6; i++) {
    suffix += ITEM_CODE_CHARS[bytes[i]! % ITEM_CODE_CHARS.length];
  }
  return `${prefix}-${suffix}`;
}

export async function generateUniqueItemCode(
  exists: (code: string) => Promise<boolean>,
  maxAttempts = 12,
): Promise<string> {
  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    const code = generateItemCode();
    if (!(await exists(code))) return code;
  }
  throw new Error("Could not generate a unique item code.");
}
