"use client";

import { useRouter } from "next/navigation";
import { useMemo, useState, useTransition } from "react";
import {
  adminCheckInByCode,
  adminCheckOutByCode,
  createEquipment,
  deleteEquipment,
  resetToSampleData,
  resolveAdminItemCode,
  updateEquipment,
  type AdminCodeLookup,
} from "@/app/admin/actions";
import { AREA_OPTIONS } from "@/lib/constants";
import { isNewItem } from "@/lib/inventory";
import { dueBackLabel } from "@/lib/reservation-availability";
import type {
  EquipmentWithUnits,
  Reservation,
  SpaceBlock,
  SpaceBooking,
} from "@/lib/types";
import { SiteFooter } from "@/components/SiteFooter";
import { BlockPeriodsPanel } from "@/components/admin/BlockPeriodsPanel";
import { PrintQrLabelsPanel } from "@/components/admin/PrintQrLabelsPanel";
import { SpaceBookingsPanel } from "@/components/admin/SpaceBookingsPanel";

type AdminDashboardProps = {
  equipment: EquipmentWithUnits[];
  reservations: Reservation[];
  spaceBookings: SpaceBooking[];
  spaceBlocks: SpaceBlock[];
};

type Tab = "space" | "items";

const fieldLabel =
  "font-mono text-[10.5px] tracking-[0.16em] text-[#6d6759]";
const underline =
  "border-0 border-b border-[#e3e0d8] bg-transparent px-0 py-2 text-[14.5px] outline-none focus:border-[#141414]";

export function AdminDashboard({
  equipment,
  reservations,
  spaceBookings,
  spaceBlocks,
}: AdminDashboardProps) {
  const router = useRouter();
  const [tab, setTab] = useState<Tab>("space");
  const [pending, startTransition] = useTransition();
  const [form, setForm] = useState({
    name: "",
    note: "",
    area: "LEGO Play",
    avail: 1,
    total: 1,
  });
  const [message, setMessage] = useState("");
  const [code, setCode] = useState("");
  const [lookup, setLookup] = useState<AdminCodeLookup | null>(null);
  const [checkoutQty, setCheckoutQty] = useState(1);
  const [checkoutBy, setCheckoutBy] = useState("");

  const openLoans = useMemo(() => {
    const byId = new Map(equipment.map((e) => [e.id, e]));
    return reservations
      .filter((r) => r.status === "out")
      .map((r) => ({
        reservation: r,
        item: byId.get(r.equipment_id),
      }))
      .filter((x) => x.item);
  }, [equipment, reservations]);

  const outByEquipment = useMemo(() => {
    const map = new Map<string, number>();
    for (const r of reservations) {
      if (r.status !== "out") continue;
      map.set(r.equipment_id, (map.get(r.equipment_id) ?? 0) + (r.out_qty || r.qty));
    }
    return map;
  }, [reservations]);

  const pendingSpaceCount = useMemo(
    () => spaceBookings.filter((b) => b.status === "pending").length,
    [spaceBookings],
  );

  const refresh = (msg: string) => {
    setMessage(msg);
    router.refresh();
  };

  const lookupHint = (() => {
    if (!code.trim()) {
      return "Every item has an autogenerated code, printed in its QR label. The app scans it with the camera — on the web, type it to check items out or in.";
    }
    if (lookup && !lookup.ok) return lookup.error;
    if (lookup?.ok && lookup.mode === "checkin") {
      return `${lookup.name} — ${lookup.loan.out_qty || lookup.loan.qty} out with ${lookup.loan.name} · due back ${lookup.dueBack}`;
    }
    if (lookup?.ok && lookup.mode === "checkout") {
      return `${lookup.name} · ${lookup.available} in the space · no open loan`;
    }
    return null;
  })();

  return (
    <div className="flex min-h-[calc(100vh-73px)] flex-col">
      <section className="no-print page-gutter flex flex-wrap items-end justify-between gap-6 pt-11">
        <div>
          <p className="mb-3 font-mono text-[12px] tracking-[0.2em] text-[#6d6759]">
            АДМІН · ADMIN
          </p>
          <h1 className="font-display text-[38px] font-normal tracking-[-0.02em]">
            Creativity Space admin
          </h1>
        </div>
        <p className="pb-1.5 font-mono text-[12px] text-[#6d6759]">
          LIVE WITH SUPABASE
        </p>
      </section>

      <div className="no-print page-gutter flex flex-wrap gap-2 pb-[34px] pt-6">
        <button
          type="button"
          onClick={() => setTab("space")}
          className="flex items-center gap-2 rounded-full px-5 py-2.5 text-[14.5px] font-semibold transition-colors"
          style={{
            background: tab === "space" ? "#141414" : "#fff",
            color: tab === "space" ? "#fff" : "#6d6759",
            border: `1px solid ${tab === "space" ? "#141414" : "#e3e0d8"}`,
          }}
        >
          Space bookings
          {pendingSpaceCount > 0 && (
            <span className="rounded-full bg-[#c8102e] px-[7px] py-0.5 font-mono text-[10.5px] text-white">
              {pendingSpaceCount}
            </span>
          )}
        </button>
        <button
          type="button"
          onClick={() => setTab("items")}
          className="flex items-center gap-2 rounded-full px-5 py-2.5 text-[14.5px] font-semibold transition-colors"
          style={{
            background: tab === "items" ? "#141414" : "#fff",
            color: tab === "items" ? "#fff" : "#6d6759",
            border: `1px solid ${tab === "items" ? "#141414" : "#e3e0d8"}`,
          }}
        >
          Items & inventory
          <span
            className="font-mono text-[10.5px]"
            style={{
              color: tab === "items" ? "#fff" : "#6d6759",
              opacity: 0.55,
            }}
          >
            {equipment.length}
          </span>
        </button>
      </div>

      {message && (
        <div className="no-print page-gutter mb-4">
          <p className="bg-[#f7f7f5] px-4 py-3 text-[14px]">{message}</p>
        </div>
      )}

      {tab === "space" && (
        <>
          <SpaceBookingsPanel
            bookings={spaceBookings}
            onDone={(msg) => refresh(msg)}
          />
          <BlockPeriodsPanel
            blocks={spaceBlocks}
            bookings={spaceBookings}
            onDone={(msg) => refresh(msg)}
          />
        </>
      )}

      {tab === "items" && (
        <>
          {openLoans.length > 0 && (
            <div className="no-print page-gutter mb-9">
              <div className="bg-[#fdf8ec]">
                <div className="flex flex-wrap items-baseline justify-between gap-2 px-[18px] pt-3">
                  <h2 className="text-[16px] font-semibold text-[#9a6e06]">
                    Currently checked out
                  </h2>
                  <p className="font-mono text-[11px] text-[#8f731c]">
                    UPDATED FROM APP
                  </p>
                </div>
                <div className="px-[18px] pt-2 pb-3.5">
                  {openLoans.map(({ reservation: r, item }) => (
                    <div
                      key={r.id}
                      className="flex flex-wrap items-center gap-2.5 py-[7px] text-[14px]"
                    >
                      <span className="shrink-0 rounded-full border border-[#e0a010] px-2 py-0.5 font-mono text-[10px] tracking-wide text-[#9a6e06]">
                        {r.out_qty || r.qty} OUT
                      </span>
                      <span className="text-[#3f3b33]">
                        <span className="font-semibold">{item!.name}</span>
                        {" — "}
                        {r.name} · due back {dueBackLabel(r)}
                      </span>
                      {r.out_at && (
                        <span className="ml-auto font-mono text-[11px] text-[#8f731c]">
                          {new Date(r.out_at).toLocaleTimeString("en-GB", {
                            hour: "2-digit",
                            minute: "2-digit",
                          })}
                        </span>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          <div className="no-print page-gutter mb-11">
            <h2 className="text-[19px] font-semibold tracking-[-0.01em]">
              Check out / check in
            </h2>
            <p className="mt-1 mb-3.5 text-[13.5px] text-[#6d6759]">
              Type the code from an item&apos;s QR label to hand it out or take
              it back.
            </p>
            <div className="flex flex-col gap-3.5 md:flex-row md:flex-wrap md:items-end">
              <label className="flex flex-col gap-1.5">
                <span className={fieldLabel}>ITEM CODE</span>
                <input
                  value={code}
                  onChange={(e) => {
                    setCode(e.target.value.toUpperCase());
                    setLookup(null);
                  }}
                  onBlur={() => {
                    if (!code.trim()) return;
                    startTransition(async () => {
                      const result = await resolveAdminItemCode(code);
                      setLookup(result);
                      if (result.ok && result.mode === "checkout") {
                        setCheckoutQty(1);
                      }
                    });
                  }}
                  placeholder="Code on the QR label, e.g. KIS-7F3K9Q"
                  className={`${underline} w-[290px] font-mono text-[14px] uppercase`}
                />
              </label>

              {lookup?.ok && lookup.mode === "checkout" && (
                <>
                  <label className="flex flex-col gap-1.5">
                    <span className={fieldLabel}>HOW MANY</span>
                    <input
                      type="number"
                      min={1}
                      max={lookup.available}
                      value={checkoutQty}
                      onChange={(e) => setCheckoutQty(Number(e.target.value))}
                      className={`${underline} w-16 font-mono`}
                    />
                  </label>
                  <label className="flex flex-col gap-1.5">
                    <span className={fieldLabel}>WHO IS TAKING IT</span>
                    <input
                      value={checkoutBy}
                      onChange={(e) => setCheckoutBy(e.target.value)}
                      placeholder="e.g. Mr. Petrov, 9A"
                      className={`${underline} w-[220px]`}
                    />
                  </label>
                  <button
                    type="button"
                    disabled={pending}
                    onClick={() =>
                      startTransition(async () => {
                        const result = await adminCheckOutByCode({
                          code: lookup.code,
                          qty: checkoutQty,
                          by: checkoutBy,
                        });
                        if (!result.ok) {
                          setMessage(result.error);
                          return;
                        }
                        setCode("");
                        setLookup(null);
                        setCheckoutBy("");
                        refresh(`Checked out ${checkoutQty}× ${lookup.name}.`);
                      })
                    }
                    className="bg-[#141414] px-[22px] py-2.5 text-[14.5px] font-semibold text-white transition-colors hover:bg-[#c8102e] disabled:opacity-60"
                  >
                    Check out →
                  </button>
                </>
              )}

              {lookup?.ok && lookup.mode === "checkin" && (
                <button
                  type="button"
                  disabled={pending}
                  onClick={() =>
                    startTransition(async () => {
                      const result = await adminCheckInByCode(lookup.code);
                      if (!result.ok) {
                        setMessage(result.error);
                        return;
                      }
                      setCode("");
                      setLookup(null);
                      refresh(`Checked in ${lookup.name}.`);
                    })
                  }
                  className="bg-[#2f9e44] px-[22px] py-2.5 text-[14.5px] font-semibold text-white transition-colors hover:bg-[#257e36] disabled:opacity-60"
                >
                  Check in {lookup.loan.out_qty || lookup.loan.qty} ✓
                </button>
              )}
            </div>
            {lookupHint && (
              <p className="mt-2.5 text-[13.5px] text-[#6d6759]">{lookupHint}</p>
            )}
          </div>

          <PrintQrLabelsPanel equipment={equipment} />

          <h2 className="no-print page-gutter mb-3.5 text-[19px] font-semibold tracking-[-0.01em]">
            Add an item
          </h2>
          <form
            className="no-print page-gutter mb-11 grid grid-cols-1 items-end gap-3 md:grid-cols-[1.5fr_2fr_150px_80px_80px_auto]"
            onSubmit={(e) => {
              e.preventDefault();
              if (!form.name.trim()) return;
              startTransition(async () => {
                await createEquipment({
                  name: form.name,
                  detail: form.note,
                  area: form.area,
                  quantity_available: form.avail,
                  quantity_total: form.total,
                });
                setForm({
                  name: "",
                  note: "",
                  area: form.area,
                  avail: 1,
                  total: 1,
                });
                refresh("Item added.");
              });
            }}
          >
            <Field label="ITEM NAME">
              <input
                value={form.name}
                onChange={(e) => setForm({ ...form, name: e.target.value })}
                placeholder="e.g. Cricut machine"
                className={`${underline} w-full`}
              />
            </Field>
            <Field label="DESCRIPTION">
              <input
                value={form.note}
                onChange={(e) => setForm({ ...form, note: e.target.value })}
                placeholder="Short note shown under the name"
                className={`${underline} w-full`}
              />
            </Field>
            <Field label="AREA">
              <select
                value={form.area}
                onChange={(e) => setForm({ ...form, area: e.target.value })}
                className={`${underline} w-full`}
              >
                {AREA_OPTIONS.map((a) => (
                  <option key={a} value={a}>
                    {a}
                  </option>
                ))}
              </select>
            </Field>
            <Field label="AVAIL">
              <input
                type="number"
                min={0}
                value={form.avail}
                onChange={(e) =>
                  setForm({ ...form, avail: Number(e.target.value) })
                }
                className={`${underline} w-full`}
              />
            </Field>
            <Field label="TOTAL">
              <input
                type="number"
                min={0}
                value={form.total}
                onChange={(e) =>
                  setForm({ ...form, total: Number(e.target.value) })
                }
                className={`${underline} w-full`}
              />
            </Field>
            <button
              type="submit"
              disabled={pending}
              className="bg-[#c8102e] px-[22px] py-2.5 text-[14.5px] font-semibold text-white hover:bg-[#a50d26] disabled:opacity-60"
            >
              + Add item
            </button>
          </form>

          <div className="no-print page-gutter mb-1.5 flex flex-wrap items-baseline gap-3">
            <h2 className="text-[19px] font-semibold tracking-[-0.01em]">
              Inventory
            </h2>
            <span className="font-mono text-[11px] tracking-[0.14em] text-[#857e6e]">
              {equipment.length} ITEMS
            </span>
          </div>

          <div className="no-print page-gutter mb-10 overflow-x-auto">
            <div className="hidden min-w-[900px] grid-cols-[40px_1.5fr_2fr_150px_132px_80px_40px] gap-3 border-b border-[#e3e0d8] py-3 font-mono text-[11px] tracking-[0.16em] text-[#6d6759] md:grid">
              <span />
              <span>ITEM</span>
              <span>DESCRIPTION</span>
              <span>AREA</span>
              <span>AVAILABLE</span>
              <span>TOTAL</span>
              <span />
            </div>

            <div className="min-w-[900px]">
              {equipment.map((item, i) => (
                <AdminRow
                  key={item.id}
                  item={item}
                  index={i}
                  outQty={outByEquipment.get(item.id) ?? 0}
                  disabled={pending}
                  onChange={(patch) =>
                    startTransition(async () => {
                      await updateEquipment(item.id, patch);
                      refresh("Saved.");
                    })
                  }
                  onDelete={() => {
                    if (!confirm(`Delete "${item.name}"?`)) return;
                    startTransition(async () => {
                      await deleteEquipment(item.id);
                      refresh("Item deleted.");
                    });
                  }}
                />
              ))}
            </div>
          </div>

          <div className="no-print page-gutter mb-6">
            <button
              type="button"
              disabled={pending}
              onClick={() => {
                if (!confirm("Replace all inventory with sample data?")) return;
                startTransition(async () => {
                  await resetToSampleData();
                  refresh("Reset to sample data.");
                });
              }}
              className="text-[14px] text-[#6d6759] underline transition-colors hover:text-[#c8102e]"
            >
              Reset to sample data
            </button>
          </div>
        </>
      )}

      <div className="no-print">
        <SiteFooter showAdmin={false} />
      </div>
    </div>
  );
}

function Field({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <label className="flex flex-col gap-1.5">
      <span className={fieldLabel}>{label}</span>
      {children}
    </label>
  );
}

function AdminRow({
  item,
  index,
  outQty,
  disabled,
  onChange,
  onDelete,
}: {
  item: EquipmentWithUnits;
  index: number;
  outQty: number;
  disabled: boolean;
  onChange: (patch: {
    name?: string;
    detail?: string;
    area?: string;
    quantity_available?: number;
    quantity_total?: number;
  }) => void;
  onDelete: () => void;
}) {
  const [name, setName] = useState(item.name);
  const [detail, setDetail] = useState(item.detail);
  const [area, setArea] = useState(item.area);
  const avail = item.quantity_available;
  const total = item.quantity_total;

  return (
    <div className="grid grid-cols-[40px_1.5fr_2fr_150px_132px_80px_40px] items-center gap-3 py-2.5 transition-colors hover:bg-[#f7f7f5]">
      <div>
        <span className="font-mono text-[12px] text-[#a89a7f]">
          {String(index + 1).padStart(2, "0")}
        </span>
        {isNewItem(item) && (
          <div className="mt-1 font-mono text-[9px] tracking-wide text-[#c8102e]">
            NEW
          </div>
        )}
        {outQty > 0 && (
          <div className="mt-1 font-mono text-[9px] tracking-wide text-[#9a6e06]">
            {outQty} OUT
          </div>
        )}
      </div>
      <div>
        <input
          value={name}
          disabled={disabled}
          onChange={(e) => setName(e.target.value)}
          onBlur={() => {
            if (name !== item.name) onChange({ name });
          }}
          className="w-full border border-transparent bg-transparent px-2.5 pt-1.5 pb-0.5 text-[15.5px] font-semibold outline-none hover:border-[#e3e0d8] focus:border-[#141414]"
        />
        <p className="px-2.5 font-mono text-[11px] text-[#857e6e]">
          {item.qr_code}
        </p>
      </div>
      <input
        value={detail}
        disabled={disabled}
        onChange={(e) => setDetail(e.target.value)}
        onBlur={() => {
          if (detail !== item.detail) onChange({ detail });
        }}
        className="w-full border border-transparent bg-transparent px-2.5 py-2 text-[14.5px] text-[#3f3b33] outline-none hover:border-[#e3e0d8] focus:border-[#141414]"
      />
      <select
        value={area}
        disabled={disabled}
        onChange={(e) => {
          setArea(e.target.value);
          onChange({ area: e.target.value });
        }}
        className="w-full border border-transparent bg-transparent px-1.5 py-2 text-[13.5px] outline-none hover:border-[#e3e0d8] focus:border-[#141414]"
      >
        {AREA_OPTIONS.map((a) => (
          <option key={a} value={a}>
            {a}
          </option>
        ))}
      </select>
      <div className="flex items-center gap-1">
        <button
          type="button"
          disabled={disabled || avail <= 0}
          onClick={() =>
            onChange({ quantity_available: Math.max(0, avail - 1) })
          }
          className="flex h-[26px] w-[26px] items-center justify-center border border-[#e3e0d8] text-[14px] transition-colors hover:bg-[#141414] hover:text-white disabled:opacity-40"
        >
          −
        </button>
        <span className="w-6 text-center font-mono text-[14px]">{avail}</span>
        <button
          type="button"
          disabled={disabled || avail >= total}
          onClick={() =>
            onChange({ quantity_available: Math.min(total, avail + 1) })
          }
          className="flex h-[26px] w-[26px] items-center justify-center border border-[#e3e0d8] text-[14px] transition-colors hover:bg-[#141414] hover:text-white disabled:opacity-40"
        >
          +
        </button>
      </div>
      <input
        type="number"
        min={0}
        value={total}
        disabled={disabled}
        onChange={(e) => {
          const t = Math.max(0, Number(e.target.value) || 0);
          onChange({
            quantity_total: t,
            quantity_available: Math.min(avail, t),
          });
        }}
        className="w-14 border border-transparent bg-transparent px-1 py-1.5 text-center font-mono text-[14px] outline-none hover:border-[#e3e0d8] focus:border-[#141414]"
      />
      <button
        type="button"
        disabled={disabled}
        onClick={onDelete}
        className="flex h-[26px] w-[26px] items-center justify-center text-[16px] text-[#857e6e] transition-colors hover:text-[#c8102e]"
        aria-label={`Delete ${item.name}`}
      >
        ×
      </button>
    </div>
  );
}
