"use client";

import { useRouter } from "next/navigation";
import { useEffect, useMemo, useRef, useState, useTransition } from "react";
import {
  adminCheckInByCode,
  adminCheckOutByCode,
  createEquipment,
  deleteEquipment,
  deleteItemRequest,
  resetToSampleData,
  resolveAdminItemCode,
  updateEquipment,
  type AdminCodeLookup,
} from "@/app/admin/actions";
import { useConfirm } from "@/components/ConfirmDialog";
import { SiteFooter } from "@/components/SiteFooter";
import { BlockPeriodsPanel } from "@/components/admin/BlockPeriodsPanel";
import {
  AdminWriteProvider,
  useAdminWrite,
} from "@/components/admin/AdminWriteFeedback";
import { AreasPanel } from "@/components/admin/AreasPanel";
import { ItemRequestsPanel } from "@/components/admin/ItemRequestsPanel";
import { PrintQrLabelsPanel } from "@/components/admin/PrintQrLabelsPanel";
import { SpaceBookingsPanel } from "@/components/admin/SpaceBookingsPanel";
import { TrainingSessionsPanel } from "@/components/admin/TrainingSessionsPanel";
import { effectiveAreaNames, type Area } from "@/lib/areas";
import { DEFAULT_AREAS } from "@/lib/constants";
import { isNewItem } from "@/lib/inventory";
import { dueBackLabel } from "@/lib/reservation-availability";
import type {
  EquipmentWithUnits,
  ItemRequest,
  Reservation,
  SpaceBlock,
  SpaceBooking,
  TrainingSession,
} from "@/lib/types";

type AdminDashboardProps = {
  equipment: EquipmentWithUnits[];
  reservations: Reservation[];
  spaceBookings: SpaceBooking[];
  spaceBlocks: SpaceBlock[];
  trainingSessions: TrainingSession[];
  itemRequests: ItemRequest[];
  areas: Area[];
};

type Tab = "space" | "items";

const fieldLabel =
  "font-mono text-[10.5px] tracking-[0.16em] text-[#6d6759]";
const underline =
  "border-0 border-b border-[#e3e0d8] bg-transparent px-0 py-2 text-[14.5px] outline-none focus:border-[#141414]";

export function AdminDashboard(props: AdminDashboardProps) {
  return (
    <AdminWriteProvider>
      <AdminDashboardInner {...props} />
    </AdminWriteProvider>
  );
}

function AdminDashboardInner({
  equipment,
  reservations,
  spaceBookings,
  spaceBlocks,
  trainingSessions,
  itemRequests,
  areas,
}: AdminDashboardProps) {
  const router = useRouter();
  const askConfirm = useConfirm();
  const { dbWrite, flashSaved, savingLabel } = useAdminWrite();
  const [tab, setTab] = useState<Tab>("space");
  const [pending, startTransition] = useTransition();
  const areaNames = useMemo(
    () =>
      effectiveAreaNames(
        areas.map((a) => a.name),
        equipment.map((e) => e.area),
      ),
    [areas, equipment],
  );
  const [form, setForm] = useState({
    name: "",
    note: "",
    area: areaNames[0] ?? DEFAULT_AREAS[0],
    avail: 1,
    total: 1,
    inSpaceOnly: false,
  });
  const [message, setMessage] = useState("");
  const [code, setCode] = useState("");
  const [lookup, setLookup] = useState<AdminCodeLookup | null>(null);
  const [checkoutQty, setCheckoutQty] = useState(1);
  const [checkoutBy, setCheckoutBy] = useState("");
  const [rows, setRows] = useState(equipment);
  const [newId, setNewId] = useState<string | null>(null);
  const [removingId, setRemovingId] = useState<string | null>(null);
  const [qrAreaReset, setQrAreaReset] = useState(0);
  const addFormRef = useRef<HTMLFormElement>(null);
  const adding = savingLabel === "ADD ITEM";

  useEffect(() => {
    setRows(equipment);
  }, [equipment]);

  useEffect(() => {
    if (!areaNames.includes(form.area) && areaNames[0]) {
      setForm((f) => ({ ...f, area: areaNames[0] }));
    }
  }, [areaNames, form.area]);

  const openLoans = useMemo(() => {
    const byId = new Map(equipment.map((e) => [e.id, e]));
    return reservations
      .filter((r) => r.status === "out")
      .map((r) => ({
        reservation: r,
        item: byId.get(r.equipment_id),
      }))
      .filter((x) => x.item);
  }, [equipment, reservations]);

  const outByEquipment = useMemo(() => {
    const map = new Map<string, number>();
    for (const r of reservations) {
      if (r.status !== "out") continue;
      map.set(r.equipment_id, (map.get(r.equipment_id) ?? 0) + (r.out_qty || r.qty));
    }
    return map;
  }, [reservations]);

  const pendingSpaceCount = useMemo(
    () =>
      spaceBookings.filter((b) => b.status === "pending").length +
      trainingSessions.filter((s) => s.status === "pending").length,
    [spaceBookings, trainingSessions],
  );

  const refresh = (msg: string) => {
    setMessage(msg);
    router.refresh();
  };

  const lookupHint = (() => {
    if (!code.trim()) {
      return "Every item has an autogenerated code, printed in its QR label. The app scans it with the camera — on the web, type it to check items out or in.";
    }
    if (lookup && !lookup.ok) return lookup.error;
    if (lookup?.ok && lookup.mode === "checkin") {
      return `${lookup.name} — ${lookup.loan.out_qty || lookup.loan.qty} out with ${lookup.loan.name} · due back ${lookup.dueBack}`;
    }
    if (lookup?.ok && lookup.mode === "checkout") {
      return `${lookup.name} · ${lookup.available} in the space · no open loan`;
    }
    if (lookup?.ok && lookup.mode === "in_space_only") {
      return `${lookup.name} · ${lookup.available} in the space · teachers can still book it for use inside the Makerspace`;
    }
    return null;
  })();

  return (
    <div className="flex min-h-[calc(100vh-73px)] flex-col">
      <section className="no-print page-gutter flex flex-wrap items-end justify-between gap-6 pt-11">
        <div>
          <p className="mb-3 font-mono text-[12px] tracking-[0.2em] text-[#6d6759]">
            АДМІН · ADMIN
          </p>
          <h1 className="font-display text-[38px] font-normal tracking-[-0.02em]">
            Design Studio admin
          </h1>
        </div>
      </section>

      <div className="no-print page-gutter flex flex-wrap gap-2 pb-[34px] pt-6">
        <button
          type="button"
          onClick={() => setTab("space")}
          className="flex items-center gap-2 rounded-full px-5 py-2.5 text-[14.5px] font-semibold transition-colors"
          style={{
            background: tab === "space" ? "#141414" : "#fff",
            color: tab === "space" ? "#fff" : "#6d6759",
            border: `1px solid ${tab === "space" ? "#141414" : "#e3e0d8"}`,
          }}
        >
          Space bookings
          {pendingSpaceCount > 0 && (
            <span className="rounded-full bg-[#c8102e] px-[7px] py-0.5 font-mono text-[10.5px] text-white">
              {pendingSpaceCount}
            </span>
          )}
        </button>
        <button
          type="button"
          onClick={() => setTab("items")}
          className="flex items-center gap-2 rounded-full px-5 py-2.5 text-[14.5px] font-semibold transition-colors"
          style={{
            background: tab === "items" ? "#141414" : "#fff",
            color: tab === "items" ? "#fff" : "#6d6759",
            border: `1px solid ${tab === "items" ? "#141414" : "#e3e0d8"}`,
          }}
        >
          Items & inventory
          <span
            className="font-mono text-[10.5px]"
            style={{
              color: tab === "items" ? "#fff" : "#6d6759",
              opacity: 0.55,
            }}
          >
            {equipment.length}
          </span>
        </button>
      </div>

      {message && (
        <div className="no-print page-gutter mb-4">
          <p className="bg-[#f7f7f5] px-4 py-3 text-[14px]">{message}</p>
        </div>
      )}

      {tab === "space" && (
        <>
          <SpaceBookingsPanel
            bookings={spaceBookings}
            onDone={(msg) => refresh(msg)}
          />
          <TrainingSessionsPanel
            sessions={trainingSessions}
            onDone={(msg) => refresh(msg)}
          />
          <BlockPeriodsPanel
            blocks={spaceBlocks}
            bookings={spaceBookings}
            onDone={(msg) => refresh(msg)}
          />
        </>
      )}

      {tab === "items" && (
        <>
          {openLoans.length > 0 && (
            <div className="no-print page-gutter mb-9">
              <div className="bg-[#fdf8ec]">
                <div className="flex flex-wrap items-baseline justify-between gap-2 px-[18px] pt-3">
                  <h2 className="text-[16px] font-semibold text-[#9a6e06]">
                    Currently checked out
                  </h2>
                  <p className="font-mono text-[11px] text-[#8f731c]">
                    UPDATED FROM APP
                  </p>
                </div>
                <div className="px-[18px] pt-2 pb-3.5">
                  {openLoans.map(({ reservation: r, item }) => (
                    <div
                      key={r.id}
                      className="flex flex-wrap items-center gap-2.5 py-[7px] text-[14px]"
                    >
                      <span className="shrink-0 rounded-full border border-[#e0a010] px-2 py-0.5 font-mono text-[10px] tracking-wide text-[#9a6e06]">
                        {r.out_qty || r.qty} OUT
                      </span>
                      <span className="text-[#3f3b33]">
                        <span className="font-semibold">{item!.name}</span>
                        {" — "}
                        {r.name} · due back {dueBackLabel(r)}
                      </span>
                      {r.out_at && (
                        <span className="ml-auto font-mono text-[11px] text-[#8f731c]">
                          {new Date(r.out_at).toLocaleTimeString("en-GB", {
                            hour: "2-digit",
                            minute: "2-digit",
                          })}
                        </span>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          <div className="no-print page-gutter mb-11">
            <h2 className="text-[19px] font-semibold tracking-[-0.01em]">
              Check out / check in
            </h2>
            <p className="mt-1 mb-3.5 text-[13.5px] text-[#6d6759]">
              Type the code from an item&apos;s QR label to hand it out or take
              it back.
            </p>
            <div className="flex flex-col gap-3.5 md:flex-row md:flex-wrap md:items-end">
              <label className="flex flex-col gap-1.5">
                <span className={fieldLabel}>ITEM CODE</span>
                <input
                  value={code}
                  onChange={(e) => {
                    setCode(e.target.value.toUpperCase());
                    setLookup(null);
                  }}
                  onBlur={() => {
                    if (!code.trim()) return;
                    startTransition(async () => {
                      const result = await resolveAdminItemCode(code);
                      setLookup(result);
                      if (result.ok && result.mode === "checkout") {
                        setCheckoutQty(1);
                      }
                    });
                  }}
                  placeholder="Code on the QR label, e.g. KIS-7F3K9Q"
                  className={`${underline} w-[290px] font-mono text-[14px] uppercase`}
                />
              </label>

              {lookup?.ok && lookup.mode === "in_space_only" && (
                <div className="flex max-w-xl items-start gap-2.5 border border-[#141414] bg-[#f4f1ea] px-3.5 py-3">
                  <span className="shrink-0 rounded-full bg-[#141414] px-2.5 py-0.5 font-mono text-[10px] tracking-[0.14em] text-[#f4f1ea]">
                    IN-SPACE ONLY
                  </span>
                  <p className="text-[14px] text-[#3f3b33]">
                    <strong>{lookup.name}</strong> stays in the Makerspace — it
                    can&apos;t be checked out or taken to another space.
                  </p>
                </div>
              )}

              {lookup?.ok && lookup.mode === "checkout" && (
                <>
                  <label className="flex flex-col gap-1.5">
                    <span className={fieldLabel}>HOW MANY</span>
                    <input
                      type="number"
                      min={1}
                      max={lookup.available}
                      value={checkoutQty}
                      onChange={(e) => setCheckoutQty(Number(e.target.value))}
                      className={`${underline} w-16 font-mono`}
                    />
                  </label>
                  <label className="flex flex-col gap-1.5">
                    <span className={fieldLabel}>WHO IS TAKING IT</span>
                    <input
                      value={checkoutBy}
                      onChange={(e) => setCheckoutBy(e.target.value)}
                      placeholder="e.g. Mr. Petrov, 9A"
                      className={`${underline} w-[220px]`}
                    />
                  </label>
                  <button
                    type="button"
                    disabled={pending}
                    onClick={() =>
                      startTransition(async () => {
                        const result = await adminCheckOutByCode({
                          code: lookup.code,
                          qty: checkoutQty,
                          by: checkoutBy,
                        });
                        if (!result.ok) {
                          setMessage(result.error);
                          return;
                        }
                        setCode("");
                        setLookup(null);
                        setCheckoutBy("");
                        flashSaved("INVENTORY");
                        refresh(`Checked out ${checkoutQty}× ${lookup.name}.`);
                      })
                    }
                    className="bg-[#141414] px-[22px] py-2.5 text-[14.5px] font-semibold text-white transition-colors hover:bg-[#c8102e] disabled:opacity-60"
                  >
                    Check out →
                  </button>
                </>
              )}

              {lookup?.ok && lookup.mode === "checkin" && (
                <button
                  type="button"
                  disabled={pending}
                  onClick={() =>
                    startTransition(async () => {
                      const result = await adminCheckInByCode(lookup.code);
                      if (!result.ok) {
                        setMessage(result.error);
                        return;
                      }
                      setCode("");
                      setLookup(null);
                      flashSaved("INVENTORY");
                      refresh(`Checked in ${lookup.name}.`);
                    })
                  }
                  className="bg-[#2f9e44] px-[22px] py-2.5 text-[14.5px] font-semibold text-white transition-colors hover:bg-[#257e36] disabled:opacity-60"
                >
                  Check in {lookup.loan.out_qty || lookup.loan.qty} ✓
                </button>
              )}
            </div>
            {lookupHint && (
              <p className="mt-2.5 text-[13.5px] text-[#6d6759]">{lookupHint}</p>
            )}
          </div>

          <PrintQrLabelsPanel
            equipment={equipment}
            areaOptions={areaNames}
            resetAreaToken={qrAreaReset}
          />

          <ItemRequestsPanel
            requests={itemRequests}
            onDone={(msg) => refresh(msg)}
            onAddToInventory={(request) => {
              setForm({
                name: request.name,
                note: request.why ?? "",
                area: form.area,
                avail: 1,
                total: 1,
                inSpaceOnly: false,
              });
              void dbWrite("REQUESTS", async () => {
                const result = await deleteItemRequest(request.id);
                if (!result.ok) throw new Error(result.error);
                refresh(
                  `Cleared request — finish adding "${request.name}" below.`,
                );
                window.setTimeout(() => {
                  const top =
                    (addFormRef.current?.getBoundingClientRect().top ?? 0) +
                    window.scrollY -
                    80;
                  window.scrollTo({ top, behavior: "smooth" });
                  addFormRef.current
                    ?.querySelector<HTMLInputElement>("input")
                    ?.focus();
                }, 100);
              });
            }}
          />

          <AreasPanel
            areas={areas}
            equipment={equipment}
            onAreaAdded={(name) => {
              setForm((f) => ({ ...f, area: name }));
              refresh(`Area “${name}” added.`);
            }}
            onAreaRemoved={(name, remaining) => {
              setForm((f) => ({
                ...f,
                area: remaining.includes(f.area)
                  ? f.area
                  : (remaining[0] ?? DEFAULT_AREAS[0]),
              }));
              setQrAreaReset((n) => n + 1);
              refresh(`Area “${name}” removed.`);
            }}
          />

          <h2 className="no-print page-gutter mb-3.5 text-[19px] font-semibold tracking-[-0.01em]">
            Add an item
          </h2>
          <form
            ref={addFormRef}
            className="no-print page-gutter mb-11 grid grid-cols-1 items-end gap-3 md:grid-cols-[minmax(140px,1.5fr)_minmax(160px,2fr)_130px_64px_64px_auto_auto]"
            onSubmit={(e) => {
              e.preventDefault();
              if (!form.name.trim() || adding) return;
              void dbWrite("ADD ITEM", async () => {
                const created = await createEquipment({
                  name: form.name,
                  detail: form.note,
                  area: form.area,
                  quantity_available: form.avail,
                  quantity_total: form.total,
                  in_space_only: form.inSpaceOnly,
                });
                setForm({
                  name: "",
                  note: "",
                  area: form.area,
                  avail: 1,
                  total: 1,
                  inSpaceOnly: false,
                });
                if (created?.id) {
                  setNewId(created.id);
                  window.setTimeout(() => setNewId(null), 1500);
                }
                refresh("Item added.");
              });
            }}
          >
            <Field label="ITEM NAME">
              <input
                value={form.name}
                onChange={(e) => setForm({ ...form, name: e.target.value })}
                placeholder="e.g. Cricut machine"
                className={`${underline} w-full`}
              />
            </Field>
            <Field label="DESCRIPTION">
              <input
                value={form.note}
                onChange={(e) => setForm({ ...form, note: e.target.value })}
                placeholder="Short note shown under the name"
                className={`${underline} w-full`}
              />
            </Field>
            <Field label="AREA">
              <select
                value={form.area}
                onChange={(e) => setForm({ ...form, area: e.target.value })}
                className={`${underline} w-full`}
              >
                {areaNames.map((a) => (
                  <option key={a} value={a}>
                    {a}
                  </option>
                ))}
              </select>
            </Field>
            <Field label="AVAIL">
              <input
                type="number"
                min={0}
                value={form.avail}
                onChange={(e) =>
                  setForm({ ...form, avail: Number(e.target.value) })
                }
                className={`${underline} w-full`}
              />
            </Field>
            <Field label="TOTAL">
              <input
                type="number"
                min={0}
                value={form.total}
                onChange={(e) =>
                  setForm({ ...form, total: Number(e.target.value) })
                }
                className={`${underline} w-full min-w-0`}
              />
            </Field>
            <button
              type="button"
              title="Item stays in the Makerspace — no check-outs"
              onClick={() =>
                setForm({ ...form, inSpaceOnly: !form.inSpaceOnly })
              }
              className="rounded-full border px-2.5 py-[11px] font-mono text-[10px] tracking-[0.06em] whitespace-nowrap transition-colors hover:border-[#141414]"
              style={{
                borderColor: form.inSpaceOnly ? "#141414" : "#e3e0d8",
                background: form.inSpaceOnly ? "#141414" : "transparent",
                color: form.inSpaceOnly ? "#f4f1ea" : "#b6b0a3",
              }}
            >
              {form.inSpaceOnly ? "✓ " : ""}IN-SPACE ONLY
            </button>
            <button
              type="submit"
              disabled={pending || adding}
              className="inline-flex items-center justify-center gap-2 px-[22px] py-2.5 text-[14.5px] font-semibold text-white disabled:opacity-60"
              style={{ background: adding ? "#a50d26" : "#c8102e" }}
            >
              {adding && (
                <span
                  className="kis-sync-spin h-[11px] w-[11px] border-2 border-[rgba(244,241,234,0.35)] border-t-white"
                  aria-hidden
                />
              )}
              {adding ? "Adding…" : "+ Add item"}
            </button>
          </form>

          <div className="no-print page-gutter mb-1.5 flex flex-wrap items-baseline gap-3">
            <h2 className="text-[19px] font-semibold tracking-[-0.01em]">
              Inventory
            </h2>
            <span className="font-mono text-[11px] tracking-[0.14em] text-[#857e6e]">
              {equipment.length} ITEMS
            </span>
          </div>

          <div className="no-print page-gutter mb-10 overflow-x-auto">
            <div className="hidden min-w-[900px] grid-cols-[40px_1.5fr_2fr_150px_132px_80px_40px] gap-3 border-b border-[#e3e0d8] py-3 font-mono text-[11px] tracking-[0.16em] text-[#6d6759] md:grid">
              <span />
              <span>ITEM</span>
              <span>DESCRIPTION</span>
              <span>AREA</span>
              <span>AVAILABLE</span>
              <span>TOTAL</span>
              <span />
            </div>

            <div className="min-w-[900px]">
              {rows.map((item, i) => (
                <AdminRow
                  key={item.id}
                  item={item}
                  index={i}
                  areaOptions={areaNames}
                  outQty={outByEquipment.get(item.id) ?? 0}
                  disabled={pending || !!removingId}
                  rowClassName={
                    item.id === removingId
                      ? "kis-admin-rowout"
                      : item.id === newId
                        ? "kis-admin-rowin"
                        : undefined
                  }
                  onChange={(patch) =>
                    startTransition(async () => {
                      await updateEquipment(item.id, patch);
                      flashSaved("INVENTORY");
                      refresh("Saved.");
                    })
                  }
                  onDelete={() => {
                    askConfirm({
                      title: "Delete this item?",
                      body: `“${item.name}” and its QR label will be removed from the inventory. This can't be undone.`,
                      action: "Delete item",
                      fn: async () => {
                        if (savingLabel) return;
                        setRemovingId(item.id);
                        await new Promise((r) => setTimeout(r, 550));
                        try {
                          await dbWrite("DELETE ITEM", async () => {
                            await deleteEquipment(item.id);
                            setRows((prev) =>
                              prev.filter((x) => x.id !== item.id),
                            );
                            refresh("Item deleted.");
                          });
                        } finally {
                          setRemovingId(null);
                        }
                      },
                    });
                  }}
                />
              ))}
            </div>
          </div>

          <div className="no-print page-gutter mb-6">
            <button
              type="button"
              disabled={pending}
              onClick={() => {
                askConfirm({
                  title: "Reset to sample data?",
                  body: "The whole inventory will be replaced with the sample set. Your added items and edits will be lost.",
                  action: "Reset data",
                  fn: () =>
                    dbWrite("RESET DATA", async () => {
                      await resetToSampleData();
                      refresh("Reset to sample data.");
                    }),
                });
              }}
              className="text-[14px] text-[#6d6759] underline transition-colors hover:text-[#c8102e]"
            >
              Reset to sample data
            </button>
          </div>
        </>
      )}

      <div className="no-print">
        <SiteFooter showAdmin={false} />
      </div>
    </div>
  );
}

function Field({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <label className="flex flex-col gap-1.5">
      <span className={fieldLabel}>{label}</span>
      {children}
    </label>
  );
}

function AdminRow({
  item,
  index,
  areaOptions,
  outQty,
  disabled,
  rowClassName,
  onChange,
  onDelete,
}: {
  item: EquipmentWithUnits;
  index: number;
  areaOptions: string[];
  outQty: number;
  disabled: boolean;
  rowClassName?: string;
  onChange: (patch: {
    name?: string;
    detail?: string;
    area?: string;
    quantity_available?: number;
    quantity_total?: number;
    in_space_only?: boolean;
  }) => void;
  onDelete: () => void;
}) {
  const [name, setName] = useState(item.name);
  const [detail, setDetail] = useState(item.detail);
  const [area, setArea] = useState(item.area);
  const avail = item.quantity_available;
  const total = item.quantity_total;
  const inSpace = item.in_space_only;

  return (
    <div
      className={`grid grid-cols-[40px_1.5fr_2fr_150px_132px_80px_40px] items-center gap-3 py-2.5 transition-colors hover:bg-[#f7f7f5] ${rowClassName ?? ""}`}
    >
      <div>
        <span className="font-mono text-[12px] text-[#a89a7f]">
          {String(index + 1).padStart(2, "0")}
        </span>
        {isNewItem(item) && (
          <div className="mt-1 font-mono text-[9px] tracking-wide text-[#c8102e]">
            NEW
          </div>
        )}
        {outQty > 0 && (
          <div className="mt-1 font-mono text-[9px] tracking-wide text-[#9a6e06]">
            {outQty} OUT
          </div>
        )}
      </div>
      <div>
        <input
          value={name}
          disabled={disabled}
          onChange={(e) => setName(e.target.value)}
          onBlur={() => {
            if (name !== item.name) onChange({ name });
          }}
          className="w-full border border-transparent bg-transparent px-2.5 pt-1.5 pb-0.5 text-[15.5px] font-semibold outline-none hover:border-[#e3e0d8] focus:border-[#141414]"
        />
        <div className="flex flex-wrap items-center gap-2 px-2.5">
          <p className="font-mono text-[11px] text-[#857e6e]">{item.qr_code}</p>
          <button
            type="button"
            disabled={disabled}
            title="Toggle: item stays in the Makerspace — no check-outs"
            onClick={() => onChange({ in_space_only: !inSpace })}
            className="rounded-full border px-2 py-0.5 font-mono text-[8.5px] tracking-[0.08em] transition-colors hover:border-[#141414] disabled:opacity-50"
            style={{
              borderColor: inSpace ? "#141414" : "#e3e0d8",
              background: inSpace ? "#141414" : "transparent",
              color: inSpace ? "#f4f1ea" : "#b6b0a3",
            }}
          >
            IN-SPACE ONLY
          </button>
        </div>
      </div>
      <input
        value={detail}
        disabled={disabled}
        onChange={(e) => setDetail(e.target.value)}
        onBlur={() => {
          if (detail !== item.detail) onChange({ detail });
        }}
        className="w-full border border-transparent bg-transparent px-2.5 py-2 text-[14.5px] text-[#3f3b33] outline-none hover:border-[#e3e0d8] focus:border-[#141414]"
      />
      <select
        value={area}
        disabled={disabled}
        onChange={(e) => {
          setArea(e.target.value);
          onChange({ area: e.target.value });
        }}
        className="w-full border border-transparent bg-transparent px-1.5 py-2 text-[13.5px] outline-none hover:border-[#e3e0d8] focus:border-[#141414]"
      >
        {areaOptions.map((a) => (
          <option key={a} value={a}>
            {a}
          </option>
        ))}
      </select>
      <div className="flex items-center gap-1">
        <button
          type="button"
          disabled={disabled || avail <= 0}
          onClick={() =>
            onChange({ quantity_available: Math.max(0, avail - 1) })
          }
          className="flex h-[26px] w-[26px] items-center justify-center border border-[#e3e0d8] text-[14px] transition-colors hover:bg-[#141414] hover:text-white disabled:opacity-40"
        >
          −
        </button>
        <span className="w-6 text-center font-mono text-[14px]">{avail}</span>
        <button
          type="button"
          disabled={disabled || avail >= total}
          onClick={() =>
            onChange({ quantity_available: Math.min(total, avail + 1) })
          }
          className="flex h-[26px] w-[26px] items-center justify-center border border-[#e3e0d8] text-[14px] transition-colors hover:bg-[#141414] hover:text-white disabled:opacity-40"
        >
          +
        </button>
      </div>
      <input
        type="number"
        min={0}
        value={total}
        disabled={disabled}
        onChange={(e) => {
          const t = Math.max(0, Number(e.target.value) || 0);
          onChange({
            quantity_total: t,
            quantity_available: Math.min(avail, t),
          });
        }}
        className="w-14 border border-transparent bg-transparent px-1 py-1.5 text-center font-mono text-[14px] outline-none hover:border-[#e3e0d8] focus:border-[#141414]"
      />
      <button
        type="button"
        disabled={disabled}
        onClick={onDelete}
        className="flex h-[26px] w-[26px] items-center justify-center text-[16px] text-[#857e6e] transition-colors hover:text-[#c8102e]"
        aria-label={`Delete ${item.name}`}
      >
        ×
      </button>
    </div>
  );
}
