"use client";

import { useEffect, useMemo, useState } from "react";
import { isNewItem } from "@/lib/inventory";
import { generateQrDataUrl } from "@/lib/qr";
import type { Equipment } from "@/lib/types";

type PrintQrLabelsPanelProps = {
  equipment: Equipment[];
  areaOptions: string[];
  resetAreaToken?: number;
};

type WhichItems = "all" | "new";

const fieldLabel =
  "font-mono text-[10.5px] tracking-[0.16em] text-[#6d6759]";
const underline =
  "border-0 border-b border-[#e3e0d8] bg-transparent px-0 py-2 text-[14.5px] outline-none focus:border-[#141414]";

export function PrintQrLabelsPanel({
  equipment,
  areaOptions,
  resetAreaToken = 0,
}: PrintQrLabelsPanelProps) {
  const [open, setOpen] = useState(false);
  const [area, setArea] = useState<string>("all");
  const [which, setWhich] = useState<WhichItems>("all");
  const [copies, setCopies] = useState(1);
  const [qrMap, setQrMap] = useState<Record<string, string>>({});

  useEffect(() => {
    setArea("all");
  }, [resetAreaToken]);

  useEffect(() => {
    if (area !== "all" && !areaOptions.includes(area)) {
      setArea("all");
    }
  }, [area, areaOptions]);

  const filtered = useMemo(() => {
    return equipment.filter((item) => {
      const areaOk = area === "all" || item.area === area;
      const whichOk = which === "all" || isNewItem(item);
      return areaOk && whichOk;
    });
  }, [equipment, area, which]);

  const labels = useMemo(() => {
    const n = Math.min(20, Math.max(1, copies || 1));
    const out: Equipment[] = [];
    for (const item of filtered) {
      for (let i = 0; i < n; i++) out.push(item);
    }
    return out;
  }, [filtered, copies]);

  useEffect(() => {
    if (!open) return;
    let cancelled = false;
    const codes = filtered.map((item) => item.qr_code);

    async function load() {
      const next: Record<string, string> = {};
      await Promise.all(
        codes.map(async (code) => {
          next[code] = await generateQrDataUrl(code);
        }),
      );
      if (!cancelled) setQrMap((prev) => ({ ...prev, ...next }));
    }

    void load();
    return () => {
      cancelled = true;
    };
  }, [open, filtered]);

  const typeCount = filtered.length;
  const copyCount = Math.min(20, Math.max(1, copies || 1));
  const totalLabels = typeCount * copyCount;

  return (
    <div className="page-gutter mb-11">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="no-print flex w-full items-center justify-between gap-4 pb-1.5 text-left"
      >
        <div>
          <h2 className="text-[19px] font-semibold tracking-[-0.01em]">
            Print QR labels
          </h2>
          <p className="mt-1.5 text-[13.5px] text-[#6d6759]">
            Codes are autogenerated by the system — one label per item type; the
            same label works for every unit.
          </p>
        </div>
        <span className="shrink-0 border border-[#141414] px-[18px] py-2 text-[14px] font-semibold transition-colors hover:bg-[#141414] hover:text-white">
          {open ? "Close" : "Print QR labels"}
        </span>
      </button>

      {open && (
        <>
          <div className="no-print flex flex-col gap-3.5 pt-3.5 pb-1.5 md:flex-row md:flex-wrap md:items-end">
            <label className="flex min-w-[140px] flex-col gap-1.5">
              <span className={fieldLabel}>AREA</span>
              <select
                value={area}
                onChange={(e) => setArea(e.target.value)}
                className={underline}
              >
                <option value="all">All areas</option>
                {areaOptions.map((a) => (
                  <option key={a} value={a}>
                    {a}
                  </option>
                ))}
              </select>
            </label>

            <label className="flex min-w-[160px] flex-col gap-1.5">
              <span className={fieldLabel}>WHICH ITEMS</span>
              <select
                value={which}
                onChange={(e) => setWhich(e.target.value as WhichItems)}
                className={underline}
              >
                <option value="all">All items</option>
                <option value="new">New this week</option>
              </select>
            </label>

            <label className="flex w-[64px] flex-col gap-1.5">
              <span className={fieldLabel}>COPIES PER ITEM</span>
              <input
                type="number"
                min={1}
                max={20}
                value={copyCount}
                onChange={(e) => setCopies(Number(e.target.value))}
                className={`${underline} font-mono`}
              />
            </label>

            <p className="flex-1 text-[13.5px] text-[#6d6759] md:pb-2">
              {typeCount === 0
                ? "No items match these criteria."
                : `${typeCount} item type${typeCount === 1 ? "" : "s"} × ${copyCount} ${copyCount === 1 ? "copy" : "copies"} = ${totalLabels} labels`}
            </p>

            <button
              type="button"
              disabled={typeCount === 0}
              onClick={() => window.print()}
              className="bg-[#141414] px-[22px] py-2.5 text-[14.5px] font-semibold text-white transition-colors hover:bg-[#c8102e] disabled:opacity-40"
            >
              Print labels →
            </button>
          </div>

          <div
            id="qr-label-sheet"
            className="grid grid-cols-[repeat(auto-fill,minmax(168px,1fr))] gap-2.5 pt-[18px]"
          >
            {labels.map((item, i) => (
              <div
                key={`${item.id}-${i}`}
                className="qr-label flex flex-col items-center gap-[7px] border border-[#141414] bg-white px-3 pb-[11px] pt-3.5"
              >
                {qrMap[item.qr_code] ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={qrMap[item.qr_code]}
                    alt={`QR ${item.qr_code}`}
                    width={92}
                    height={92}
                    className="h-[92px] w-[92px]"
                    style={{ imageRendering: "pixelated" }}
                  />
                ) : (
                  <div className="h-[92px] w-[92px] bg-[#f7f7f5]" />
                )}
                <p className="text-center text-[12.5px] font-semibold leading-[1.3] text-[#141414]">
                  {item.name}
                </p>
                <p className="font-mono text-[11px] text-[#3f3b33]">
                  {item.qr_code}
                </p>
                <p className="font-mono text-[7.5px] tracking-[0.2em] text-[#857e6e]">
                  KIS DESIGN STUDIO
                </p>
              </div>
            ))}
          </div>
        </>
      )}
    </div>
  );
}
